/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RUTA;

import controlador.ControladorEstacion;
import controlador.ControladorRutas;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author edison
 */
public class Ventana_insertar_rutas extends javax.swing.JFrame {
    private File fichero;
    int imagen_num = 0;
    ArrayList<String> estacion_añadir = new ArrayList<>();
    
    /**
     * Creates new form Ventana_rutas
     */
    public Ventana_insertar_rutas() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
         setResizable(false);
        llenarEstaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_nombre_ruta = new javax.swing.JTextField();
        texto_descipcion_ruta = new java.awt.TextArea();
        boton_registrar_ruta = new javax.swing.JButton();
        boton_imagen_ruta = new javax.swing.JButton();
        foto_ruta = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        anadir_estacion = new javax.swing.JToggleButton();
        boton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/metrocali11.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("*Nombre:");

        jLabel3.setText("*Estaciones:");

        jLabel4.setText("*Imagen:");

        campo_nombre_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombre_rutaActionPerformed(evt);
            }
        });

        boton_registrar_ruta.setText("Registrar");
        boton_registrar_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrar_rutaActionPerformed(evt);
            }
        });

        boton_imagen_ruta.setText("Escoger Imagen");
        boton_imagen_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imagen_rutaActionPerformed(evt);
            }
        });

        foto_ruta.setText("                                  FOTO");

        anadir_estacion.setText("Añadir");
        anadir_estacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_estacionActionPerformed(evt);
            }
        });

        boton_volver.setText("Volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_imagen_ruta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_registrar_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nombre_ruta)
                            .addComponent(foto_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(texto_descipcion_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(anadir_estacion)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_volver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_nombre_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anadir_estacion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(texto_descipcion_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foto_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_imagen_ruta)
                            .addComponent(boton_registrar_ruta))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombre_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombre_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombre_rutaActionPerformed

    private void boton_registrar_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrar_rutaActionPerformed
        // TODO add your handling code here:
        
     
        String nombre_ruta;
        String descripcion;
        String ruta_imagen;
        
        if((campo_nombre_ruta.getText().trim().length() !=0)&& (texto_descipcion_ruta.getText().trim().length()>=3)&& imagen_num>0)
        {
            nombre_ruta = campo_nombre_ruta.getText();
            descripcion = texto_descipcion_ruta.getText();
            System.out.println(fichero);
            ruta_imagen = fichero.toString();
            ControladorRutas controlador = new ControladorRutas();
            int num = controlador.insertarRuta(nombre_ruta,descripcion,ruta_imagen);
            
            int num2 = controlador.insertarEstacionRuta(nombre_ruta,estacion_añadir);
            
            JOptionPane.showMessageDialog(null, "Ruta Añadida");
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos y su respectiva imagen");
            
        }
       
        
    }//GEN-LAST:event_boton_registrar_rutaActionPerformed

    private void boton_imagen_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imagen_rutaActionPerformed
        // TODO add your handling code here:
        int resultado;
        
        File_Chooser escoger = new File_Chooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter ("JPG y PNG", "jpg", "png");
        
        escoger.chooser.setFileFilter(filtro);
        
        resultado = escoger.chooser.showOpenDialog(null);
        
        if (JFileChooser.APPROVE_OPTION == resultado){
            fichero = escoger.chooser.getSelectedFile();
            
            try {
                ImageIcon imagen = new ImageIcon(fichero.toString());
                
                Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(foto_ruta.getWidth(), foto_ruta.getHeight(), Image.SCALE_DEFAULT));
                
                foto_ruta.setText(null);
                
                foto_ruta.setIcon(icono);
                
                imagen_num = 1;
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error al abrir la imagen: " + e);
            }
        }
        
    }//GEN-LAST:event_boton_imagen_rutaActionPerformed

    private void anadir_estacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_estacionActionPerformed
        // TODO add your handling code here:
       
        
        estacion_añadir.add(jComboBox1.getSelectedItem().toString());
        int posicion = jComboBox1.getSelectedIndex();
        System.out.println("posicion"+posicion);
        texto_descipcion_ruta.append(jComboBox1.getSelectedItem().toString()+" ");
        jComboBox1.removeItemAt(posicion);
      
        
        
    }//GEN-LAST:event_anadir_estacionActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed

        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed

     /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton anadir_estacion;
    private javax.swing.JButton boton_imagen_ruta;
    private javax.swing.JButton boton_registrar_ruta;
    private javax.swing.JButton boton_volver;
    private javax.swing.JTextField campo_nombre_ruta;
    private javax.swing.JLabel foto_ruta;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea texto_descipcion_ruta;
    // End of variables declaration//GEN-END:variables

    private void llenarEstaciones() {
       
        ArrayList<String> estaciones = new ArrayList<>();
        ControladorEstacion controlador = new ControladorEstacion ();
        estaciones = controlador.listaEstaciones();
        
        for(int i = 0; i<estaciones.size(); i++){
            
            jComboBox1.addItem(estaciones.get(i));
            
            
        }
        
    
    
    }
}
