/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.TARJETA;

import controlador.ControladorTarjeta;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import logica.Tarjeta;

/**
 *
 * @author natha
 */
public class Tarjeta_generica extends javax.swing.JFrame {
    ControladorTarjeta controladorTarjeta;
    /**
     * Creates new form tarjeta_generica
     */
    public Tarjeta_generica() {
        initComponents();
        controladorTarjeta=new ControladorTarjeta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campo_id_tarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campo_saldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_estado = new javax.swing.JTextField();
        boton_vender_tarjeta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campo_estacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_vendedor = new javax.swing.JTextField();
        boton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/metrocali11.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("VENTA TARJETA GENERICA");

        jLabel1.setText("No. de Tarjeta:");

        campo_id_tarjeta.setEditable(false);

        jLabel2.setText("Saldo:");

        campo_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_saldoActionPerformed(evt);
            }
        });
        campo_saldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_saldoKeyTyped(evt);
            }
        });

        jLabel4.setText("Estado:");

        campo_estado.setEditable(false);
        campo_estado.setText("Activa");

        boton_vender_tarjeta.setText("Vender Tarjeta");
        boton_vender_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_vender_tarjetaActionPerformed(evt);
            }
        });

        jLabel5.setText("Estación de Compra:");

        jLabel7.setText("Empleado Vendedor:");

        boton_volver.setText("Volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_volver)
                .addGap(37, 37, 37)
                .addComponent(jLabel43)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_vender_tarjeta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_saldo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(campo_estacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_id_tarjeta)
                            .addComponent(campo_vendedor))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43))
                    .addComponent(boton_volver))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_id_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campo_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campo_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(boton_vender_tarjeta)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_saldoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_campo_saldoActionPerformed

    private void campo_saldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_saldoKeyTyped
        // TODO add your handling code here:
        
         if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_campo_saldoKeyTyped

    private void boton_vender_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_vender_tarjetaActionPerformed
        double saldo,deuda;
        String estado,empleado_vendedor,nombre_estacion;
        
        saldo=(double)Integer.parseInt(campo_saldo.getText());
        deuda=0;
        
        estado=campo_estado.getText();
        empleado_vendedor=campo_vendedor.getText();
        nombre_estacion=campo_estacion.getText();
        
        Tarjeta t =new Tarjeta();
        t.setSaldo(saldo);
        t.setDeuda(deuda);
        t.setEstado(estado);
        t.setCedula_empleado(empleado_vendedor);
        t.setNombre_estacion(nombre_estacion);
        
        int numfilas=controladorTarjeta.registrarTarjeta(t);
        
        if(numfilas==1){
            JOptionPane.showMessageDialog(null, "La tarjeta ha sido registrada con exito.");
            campo_saldo.setText("");
            campo_vendedor.setText("");
            campo_estacion.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al registrar la tarjeta.");
        }
        
    }//GEN-LAST:event_boton_vender_tarjetaActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
        Ventana_tarjetas ventana_tarjetas= new Ventana_tarjetas();
        ventana_tarjetas.toFront();
        ventana_tarjetas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed
    
    /*public static void main(String args[]) {

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjeta_generica().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_vender_tarjeta;
    private javax.swing.JButton boton_volver;
    private javax.swing.JTextField campo_estacion;
    private javax.swing.JTextField campo_estado;
    private javax.swing.JTextField campo_id_tarjeta;
    private javax.swing.JTextField campo_saldo;
    private javax.swing.JTextField campo_vendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
