/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.TARJETA;

import controlador.ControladorTarjeta;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author natha
 */
public class Tarjeta_personalizada extends javax.swing.JFrame {
    ControladorTarjeta controladorTarjeta;
    /**
     * Creates new form tarjeta_personalizada
     */
    public Tarjeta_personalizada() {
       initComponents();
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
         setResizable(false);
        controladorTarjeta=new ControladorTarjeta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campo_id_tarjeta = new javax.swing.JTextField();
        boton_verificar_pasajero = new javax.swing.JButton();
        campo_cedula = new javax.swing.JTextField();
        boton_vender = new javax.swing.JButton();
        etiqueta_verificar = new javax.swing.JLabel();
        boton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/metrocali11.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("TARJETA PERSONALIZADA");

        jLabel1.setText("No. de Tarjeta:");

        jLabel6.setText("Cedula del pasajero:");

        boton_verificar_pasajero.setText("Verificar Pasajero");
        boton_verificar_pasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verificar_pasajeroActionPerformed(evt);
            }
        });

        boton_vender.setText("Personalizar Tarjeta");
        boton_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_venderActionPerformed(evt);
            }
        });

        etiqueta_verificar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        boton_volver.setText("Volver");
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_vender))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_verificar_pasajero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campo_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(campo_id_tarjeta)
                            .addComponent(etiqueta_verificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(boton_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43))
                    .addComponent(boton_volver))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campo_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(etiqueta_verificar)
                .addGap(7, 7, 7)
                .addComponent(boton_verificar_pasajero)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_id_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(boton_vender)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_venderActionPerformed
        String cedula_pasajero;
        int id_tarjeta;
        int resultado=-1;
        
        id_tarjeta=Integer.parseInt(campo_id_tarjeta.getText());
        cedula_pasajero=campo_cedula.getText();
        
        int verificacion=controladorTarjeta.verificarPasajero(cedula_pasajero);
        
        if(verificacion==1){
            etiqueta_verificar.setForeground(Color.GREEN);
            etiqueta_verificar.setText("pasajero valido");
            resultado=controladorTarjeta.asignarPersonalizada(cedula_pasajero, id_tarjeta);
        }else if(verificacion==0){
            etiqueta_verificar.setForeground(Color.RED);
            etiqueta_verificar.setText("pasajero invalido");
        }
        
        
        if(resultado==1){
            JOptionPane.showMessageDialog(null, "La tarjeta personalizada fue asiganada exitosamente.");
            campo_id_tarjeta.setText("");
            campo_cedula.setText("");
            etiqueta_verificar.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al asignar la tarjeta personalizada.");
        }
    }//GEN-LAST:event_boton_venderActionPerformed

    private void boton_verificar_pasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verificar_pasajeroActionPerformed
        String cedula_pasajero=campo_cedula.getText();
        int verificacion=controladorTarjeta.verificarPasajero(cedula_pasajero);
        
        if(verificacion==1){
            etiqueta_verificar.setForeground(Color.GREEN);
            etiqueta_verificar.setText("pasajero valido");
        }else if(verificacion==0){
            etiqueta_verificar.setForeground(Color.RED);
            etiqueta_verificar.setText("pasajero invalido");
        }
    }//GEN-LAST:event_boton_verificar_pasajeroActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
       
        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed
    
    /*public static void main(String args[]) {

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjeta_personalizada().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_vender;
    private javax.swing.JButton boton_verificar_pasajero;
    private javax.swing.JButton boton_volver;
    private javax.swing.JTextField campo_cedula;
    private javax.swing.JTextField campo_id_tarjeta;
    private javax.swing.JLabel etiqueta_verificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
